// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vrcgccxrfveurwshtsvz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZyY2djY3hyZnZldXJ3c2h0c3Z6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4MjM2NjksImV4cCI6MjA2MTM5OTY2OX0.4lNosMGNEQ--UZL_xqrQauM--ZEzVcq0o87ODLLOD98";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);